# Generated by Django 5.1.4 on 2025-01-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_products', '0002_product_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
